# This is the network config written by 'subiqu
network:
  ethernets:
    enp129s0f0np0:
      dhcp4: false
    enp129s0f1np1:
      dhcp4: false
  bonds:
    bond0:
      interfaces: [enp129s0f0np0, enp129s0f1np1]
      parameters:
        mode: active-backup
        mii-monitor-interval: 1
      addresses:
        - 10.5.10.110/24
      routes:
        - to: default
          via: 10.5.10.254
      nameservers:
        addresses:
          - 168.126.63.1


